# **Obtención y preparación de datos**
# OD02. Numpy Array

In [ ]:
import numpy as np #Importar numpy, por convención el alias es np

### <font color='blue'>**¿Qué es un matriz?**</font>

Una matriz (o arreglo) es la estructura de datos central de la biblioteca NumPy. Una matriz es una cuadrícula de valores y contiene información sobre los datos sin procesar, cómo ubicar un elemento y cómo interpretar un elemento. Tiene una cuadrícula de elementos que se pueden indexar de varias formas. Los elementos son todos del mismo tipo, denominados **array dtype**.

<img src='https://drive.google.com/uc?export=view&id=1gzNzhv_B2Dcu5NzozSAXqmNp3zio6Mc1' width="500" align="center" style="margin-right: 20px">

**Nota: es posible referirse la estructura ndarray de NumPy de las siguientes formas: array, arreglo, y/o matriz.**

Una matriz puede ser indexada por una tupla de enteros no negativos, por booleanos, por otra matriz o por enteros. El rango de la matriz es el número de dimensiones. La forma de la matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Una forma en que podemos inicializar matrices NumPy es a partir de listas de Python, utilizando listas anidadas para datos bidimensionales o de mayor dimensión. Por ejemplo:


## <font color="orange"> El rango de la matriz es el número de dimensiones</font>

In [ ]:
A = np.array([1, 2, 3, 4, 5]) #1 dimensión
print(A)

[1 2 3 4 5]


o

In [ ]:
A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]]) #2 dimensiones
print(A)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


Podemos acceder a los elementos de la matriz utilizando **corchetes**. Cuando acceda a los elementos de la matriz, recuerde que la **indexación en NumPy comienza en 0**. Eso significa que si desea acceder al primer elemento de su matriz, estará accediendo al elemento "0".

<img src='https://drive.google.com/uc?export=view&id=18qtkEag596pYiUWuULj1f88v4L-1DEnq' width="500" align="center" style="margin-right: 20px">

In [ ]:
print(A[:,2]) #Selecciona columna

[ 3  9 15 21]


In [ ]:
print(A[2,1]) #Selecciona elemento

14


Una matriz N-dimensional es una matriz con cualquier número de dimensiones. También puede encontrar matrices 1D o matriz unidimensional, 2D o matriz bidimensional, etc.

La clase ndarray de NumPy se utiliza para representar tanto matrices como vectores. Un vector es una matriz con una sola dimensión (no hay diferencia entre los vectores de fila y columna), mientras que una matriz se refiere a una matriz con dos dimensiones. Para matrices tridimensionales o superiores, el término tensor también se usa comúnmente.

#### <font color='blue'>**¿Cuáles son los atributos de una matriz?**</font>

Una matriz suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. El número de dimensiones y elementos de una matriz se define por su forma. La forma de una matriz es una tupla de números enteros no negativos que especifican los tamaños de cada dimensión.

En NumPy, las dimensiones se llaman ejes. Esto significa que si tiene una matriz 2D que se ve así:

<font color="red">tensor es la puerta a la librería TensorFlow</font>

In [ ]:
print(type([[0., 0., 0.], [1., 1., 1.]]))  #class list
print(type(np.array([[0., 0., 0.], [1., 1., 1.]]))) #class ndarray
[[0., 0., 0.],
 [1., 1., 1.]]   

<class 'list'>
<class 'numpy.ndarray'>


[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

Su matriz tiene 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.

Al igual que en otros objetos contenedores de Python, se puede acceder y modificar el contenido de una matriz indexando o dividiendo la matriz. A diferencia de los objetos contenedores típicos, diferentes matrices pueden compartir los mismos datos, por lo que los cambios realizados en una matriz pueden ser visibles en otra.

Los atributos de la matriz reflejan información intrínseca a la propia matriz. Si necesita obtener, o incluso establecer, propiedades de una matriz sin crear una nueva matriz, a menudo puede acceder a una matriz a través de sus atributos. Para detalles y más información pinche <a href="https://numpy.org/devdocs/reference/arrays.ndarray.html#arrays-ndarray">aquí</a>. 

## <font color='darkorange'>Algunos atributos interesantes de los arrays:</font>

In [ ]:
# Tupla con dimensiones del array
A.shape

(4, 3)

In [ ]:
# Número de dimensiones
A.ndim

2

In [ ]:
# Número de elementos del array
A.size

12

In [ ]:
# Longitud de un elemento del array en bytes.
A.itemsize

8

In [ ]:
# Total bytes de los elementos del array.
A.nbytes

96

In [ ]:
# Transpuesta del array
A.T

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21]])

In [ ]:
# Iterador 1-D del array
print('Impresión del array A sobre una lista:\n')
print([i for i in A]) #En este caso se imprime el array por filas en una lista
print('\nImpresión del array A sobre una lista (con iterador 1-D):\n')
print([i for i in A.flat]) #Imprime el array como lista

Impresión del array A sobre una lista:

[array([1, 2, 3]), array([7, 8, 9]), array([13, 14, 15]), array([19, 20, 21])]

Impresión del array A sobre una lista (con iterador 1-D):

[1, 2, 3, 7, 8, 9, 13, 14, 15, 19, 20, 21]


## <font color='green'>**Actividad 1**</font>

A partir de la matriz A definida anteriomente:

1. Indicar el rango y la forma de la matriz A.
2. Crear un vector *a1* que corresponda a la segunda columna de la matriz A.
3. Crear una matriz *a2* que incluya los elementos de las filas 2 a 4 y de las columnas 2 a 3 de la matriz A.
4. Crear un vector *a3* que contenga los elementos A[0,0], A[1,2], A[0,1], A[3,2], A[2,2] y A[1,1]
5. Crear una matriz *a4* de 2x3 con las primeras dos filas.
6. Crear una matriz *a5* que contenga la última y la primera fila de la matriz A.

In [ ]:
#Solución

dimensiones = A.ndim # rango matriz ndim
forma = A.shape # forma shape
tamano = A.size # cantidad de elementos de la matriz
a1 =A[:,1]  # Segunda columna
a2 =A[1:,1:] # filas 2 a 4 y columnas 2 a 3
a3 =np.array([A[0,0],A[1,2],A[0,1],A[3,2],A[2,2],A[1,1]]) # elementos [0,0], [1,2], [0,1], [3,2], [2,2], [1,1] 
a4 =A[:2,:] # Las dos primeras filas
a5 =A[[3,0],:] # la primera y última fila de la matriz

In [ ]:
print(f"n dim:  {dimensiones}")
print()
print(f"forma:  {forma}")
print()
print(f"n elementos:  {tamano}")
print()
print(f"a1 =  {a1}")
print()
print(f"a2 =  {a2}")
print()
print(f"a3 =  {a3}")
print()
print(f"a4 =  {a4}")
print()
print(f"a5 =  {a5}")

n dim:  2

forma:  (4, 3)

n elementos:  12

a1 =  [ 2  8 14 20]

a2 =  [[ 8  9]
 [14 15]
 [20 21]]

a3 =  [ 1  9  2 21 15  8]

a4 =  [[1 2 3]
 [7 8 9]]

a5 =  [[19 20 21]
 [ 1  2  3]]


<font color='green'>**Fin actividad 1**</font>